/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface FigmaAttachmentAttachToKeyRequest {
    projectId: string;
    figmaAttachmentId: string;
    id: string;
    xPhraseAppOTP?: string;
    branch?: string;
}

export interface FigmaAttachmentDetachFromKeyRequest {
    projectId: string;
    figmaAttachmentId: string;
    id: string;
    xPhraseAppOTP?: string;
    branch?: string;
}

/**
 * 
 */
export class KeysFigmaAttachmentsApi extends runtime.BaseAPI {

    /**
     * Attach the Figma attachment to a key
     * Attach the Figma attachment to a key
     */
    async figmaAttachmentAttachToKeyRaw(requestParameters: FigmaAttachmentAttachToKeyRequest): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling figmaAttachmentAttachToKey.');
        }

        if (requestParameters.figmaAttachmentId === null || requestParameters.figmaAttachmentId === undefined) {
            throw new runtime.RequiredError('figmaAttachmentId','Required parameter requestParameters.figmaAttachmentId was null or undefined when calling figmaAttachmentAttachToKey.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling figmaAttachmentAttachToKey.');
        }

        const queryParameters: any = {};

        if (requestParameters.branch !== undefined) {
            queryParameters['branch'] = requestParameters.branch;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPhraseAppOTP !== undefined && requestParameters.xPhraseAppOTP !== null) {
            headerParameters['X-PhraseApp-OTP'] = String(requestParameters.xPhraseAppOTP);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Token authentication
        }

        const response = await this.request({
            path: `/projects/{project_id}/figma_attachments/{figma_attachment_id}/keys`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"figma_attachment_id"}}`, encodeURIComponent(String(requestParameters.figmaAttachmentId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Attach the Figma attachment to a key
     * Attach the Figma attachment to a key
     */
    async figmaAttachmentAttachToKey(requestParameters: FigmaAttachmentAttachToKeyRequest): Promise<any> {
        const response = await this.figmaAttachmentAttachToKeyRaw(requestParameters);
        return await response.value();
    }

    /**
     * Detach the Figma attachment from a key
     * Detach the Figma attachment from a key
     */
    async figmaAttachmentDetachFromKeyRaw(requestParameters: FigmaAttachmentDetachFromKeyRequest): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling figmaAttachmentDetachFromKey.');
        }

        if (requestParameters.figmaAttachmentId === null || requestParameters.figmaAttachmentId === undefined) {
            throw new runtime.RequiredError('figmaAttachmentId','Required parameter requestParameters.figmaAttachmentId was null or undefined when calling figmaAttachmentDetachFromKey.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling figmaAttachmentDetachFromKey.');
        }

        const queryParameters: any = {};

        if (requestParameters.branch !== undefined) {
            queryParameters['branch'] = requestParameters.branch;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPhraseAppOTP !== undefined && requestParameters.xPhraseAppOTP !== null) {
            headerParameters['X-PhraseApp-OTP'] = String(requestParameters.xPhraseAppOTP);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Token authentication
        }

        const response = await this.request({
            path: `/projects/{project_id}/figma_attachments/{figma_attachment_id}/keys/{id}`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"figma_attachment_id"}}`, encodeURIComponent(String(requestParameters.figmaAttachmentId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Detach the Figma attachment from a key
     * Detach the Figma attachment from a key
     */
    async figmaAttachmentDetachFromKey(requestParameters: FigmaAttachmentDetachFromKeyRequest): Promise<any> {
        const response = await this.figmaAttachmentDetachFromKeyRaw(requestParameters);
        return await response.value();
    }

}
