/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CustomMetadataPropertyCreate422Response,
    CustomMetadataPropertyCreate422ResponseFromJSON,
    CustomMetadataPropertyCreate422ResponseToJSON,
    ProjectsQualityPerformanceScore200Response,
    ProjectsQualityPerformanceScore200ResponseFromJSON,
    ProjectsQualityPerformanceScore200ResponseToJSON,
    ProjectsQualityPerformanceScoreRequest,
    ProjectsQualityPerformanceScoreRequestFromJSON,
    ProjectsQualityPerformanceScoreRequestToJSON,
} from '../models';

export interface ProjectsQualityPerformanceScoreOperationRequest {
    id: string;
    projectsQualityPerformanceScoreRequest: ProjectsQualityPerformanceScoreRequest;
    xPhraseAppOTP?: string;
}

/**
 * 
 */
export class QualityPerformanceScoreApi extends runtime.BaseAPI {

    /**
     * Get project\'s translations\' quality performance scores
     * Get project\'s translations\' quality performance scores
     */
    async projectsQualityPerformanceScoreRaw(requestParameters: ProjectsQualityPerformanceScoreOperationRequest): Promise<runtime.ApiResponse<ProjectsQualityPerformanceScore200Response>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling projectsQualityPerformanceScore.');
        }

        if (requestParameters.projectsQualityPerformanceScoreRequest === null || requestParameters.projectsQualityPerformanceScoreRequest === undefined) {
            throw new runtime.RequiredError('projectsQualityPerformanceScoreRequest','Required parameter requestParameters.projectsQualityPerformanceScoreRequest was null or undefined when calling projectsQualityPerformanceScore.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xPhraseAppOTP !== undefined && requestParameters.xPhraseAppOTP !== null) {
            headerParameters['X-PhraseApp-OTP'] = String(requestParameters.xPhraseAppOTP);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Token authentication
        }

        const response = await this.request({
            path: `/projects/{id}/quality_performance_score`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectsQualityPerformanceScoreRequestToJSON(requestParameters.projectsQualityPerformanceScoreRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsQualityPerformanceScore200ResponseFromJSON(jsonValue));
    }

    /**
     * Get project\'s translations\' quality performance scores
     * Get project\'s translations\' quality performance scores
     */
    async projectsQualityPerformanceScore(requestParameters: ProjectsQualityPerformanceScoreOperationRequest): Promise<ProjectsQualityPerformanceScore200Response> {
        const response = await this.projectsQualityPerformanceScoreRaw(requestParameters);
        return await response.value();
    }

}
