/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BitbucketSyncImportParameters
 */
export interface BitbucketSyncImportParameters {
    /**
     * Account ID to specify the actual account the project should be created in. Required if the requesting user is a member of multiple accounts.
     * @type {string}
     * @memberof BitbucketSyncImportParameters
     */
    accountId?: string;
}

export function BitbucketSyncImportParametersFromJSON(json: any): BitbucketSyncImportParameters {
    return BitbucketSyncImportParametersFromJSONTyped(json, false);
}

export function BitbucketSyncImportParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BitbucketSyncImportParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
    };
}

export function BitbucketSyncImportParametersToJSON(value?: BitbucketSyncImportParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_id': value.accountId,
    };
}


