/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlacklistedKeyCreateParameters
 */
export interface BlacklistedKeyCreateParameters {
    /**
     * Blacklisted key name
     * @type {string}
     * @memberof BlacklistedKeyCreateParameters
     */
    name?: string;
}

export function BlacklistedKeyCreateParametersFromJSON(json: any): BlacklistedKeyCreateParameters {
    return BlacklistedKeyCreateParametersFromJSONTyped(json, false);
}

export function BlacklistedKeyCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlacklistedKeyCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function BlacklistedKeyCreateParametersToJSON(value?: BlacklistedKeyCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


