/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BranchComparisonDiff,
    BranchComparisonDiffFromJSON,
    BranchComparisonDiffFromJSONTyped,
    BranchComparisonDiffToJSON,
} from './';

/**
 * Comparison result of a branch against its base branch. Top-level properties correspond to resource types. Each resource type lists changes made in the base branch (`base_changes`), changes made in the feature branch (`head_changes`), and conflicting entries (`conflicts`). 
 * @export
 * @interface BranchComparison
 */
export interface BranchComparison {
    /**
     * 
     * @type {BranchComparisonDiff}
     * @memberof BranchComparison
     */
    translationKeys?: BranchComparisonDiff;
    /**
     * 
     * @type {BranchComparisonDiff}
     * @memberof BranchComparison
     */
    translations?: BranchComparisonDiff;
    /**
     * 
     * @type {BranchComparisonDiff}
     * @memberof BranchComparison
     */
    locales?: BranchComparisonDiff;
    /**
     * 
     * @type {BranchComparisonDiff}
     * @memberof BranchComparison
     */
    tags?: BranchComparisonDiff;
}

export function BranchComparisonFromJSON(json: any): BranchComparison {
    return BranchComparisonFromJSONTyped(json, false);
}

export function BranchComparisonFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchComparison {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'translationKeys': !exists(json, 'translation_keys') ? undefined : BranchComparisonDiffFromJSON(json['translation_keys']),
        'translations': !exists(json, 'translations') ? undefined : BranchComparisonDiffFromJSON(json['translations']),
        'locales': !exists(json, 'locales') ? undefined : BranchComparisonDiffFromJSON(json['locales']),
        'tags': !exists(json, 'tags') ? undefined : BranchComparisonDiffFromJSON(json['tags']),
    };
}

export function BranchComparisonToJSON(value?: BranchComparison | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'translation_keys': BranchComparisonDiffToJSON(value.translationKeys),
        'translations': BranchComparisonDiffToJSON(value.translations),
        'locales': BranchComparisonDiffToJSON(value.locales),
        'tags': BranchComparisonDiffToJSON(value.tags),
    };
}


