/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchCreateParameters
 */
export interface BranchCreateParameters {
    /**
     * Name of the branch
     * @type {string}
     * @memberof BranchCreateParameters
     */
    name: string;
}

export function BranchCreateParametersFromJSON(json: any): BranchCreateParameters {
    return BranchCreateParametersFromJSONTyped(json, false);
}

export function BranchCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function BranchCreateParametersToJSON(value?: BranchCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


