/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Translation,
    TranslationFromJSON,
    TranslationFromJSONTyped,
    TranslationToJSON,
} from './';

/**
 * 
 * @export
 * @interface CheckIssue
 */
export interface CheckIssue {
    /**
     * 
     * @type {string}
     * @memberof CheckIssue
     */
    id?: string;
    /**
     * Identifier of the check that reported this issue. One of: `translation_content_length`, `translation_placeholder_usage`, `translation_glossary_usage`.
     * @type {string}
     * @memberof CheckIssue
     */
    checkName?: CheckIssueCheckNameEnum;
    /**
     * Current state of the check issue. One of: `active`, `solved`, `dismissed`.
     * @type {string}
     * @memberof CheckIssue
     */
    state?: CheckIssueStateEnum;
    /**
     * Human-readable description of the reported issue, always in English. This message is intended for display only. Its wording may change at any time and it should not be parsed or relied upon programmatically.
     * @type {string}
     * @memberof CheckIssue
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof CheckIssue
     */
    dismissedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CheckIssue
     */
    solvedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CheckIssue
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckIssue
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Translation}
     * @memberof CheckIssue
     */
    translation?: Translation;
}

export function CheckIssueFromJSON(json: any): CheckIssue {
    return CheckIssueFromJSONTyped(json, false);
}

export function CheckIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckIssue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'checkName': !exists(json, 'check_name') ? undefined : json['check_name'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'dismissedAt': !exists(json, 'dismissed_at') ? undefined : (json['dismissed_at'] === null ? null : new Date(json['dismissed_at'])),
        'solvedAt': !exists(json, 'solved_at') ? undefined : (json['solved_at'] === null ? null : new Date(json['solved_at'])),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'translation': !exists(json, 'translation') ? undefined : TranslationFromJSON(json['translation']),
    };
}

export function CheckIssueToJSON(value?: CheckIssue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'check_name': value.checkName,
        'state': value.state,
        'description': value.description,
        'dismissed_at': value.dismissedAt === undefined ? undefined : (value.dismissedAt === null ? null : value.dismissedAt.toISOString()),
        'solved_at': value.solvedAt === undefined ? undefined : (value.solvedAt === null ? null : value.solvedAt.toISOString()),
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'translation': TranslationToJSON(value.translation),
    };
}

/**
* @export
* @enum {string}
*/
export enum CheckIssueCheckNameEnum {
    ContentLength = 'translation_content_length',
    PlaceholderUsage = 'translation_placeholder_usage',
    GlossaryUsage = 'translation_glossary_usage'
}
/**
* @export
* @enum {string}
*/
export enum CheckIssueStateEnum {
    Active = 'active',
    Solved = 'solved',
    Dismissed = 'dismissed'
}


