/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitlabSyncHistoryErrorsInner
 */
export interface GitlabSyncHistoryErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof GitlabSyncHistoryErrorsInner
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GitlabSyncHistoryErrorsInner
     */
    message?: string;
}

export function GitlabSyncHistoryErrorsInnerFromJSON(json: any): GitlabSyncHistoryErrorsInner {
    return GitlabSyncHistoryErrorsInnerFromJSONTyped(json, false);
}

export function GitlabSyncHistoryErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitlabSyncHistoryErrorsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function GitlabSyncHistoryErrorsInnerToJSON(value?: GitlabSyncHistoryErrorsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
        'message': value.message,
    };
}


