/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GlossaryCreateParameters
 */
export interface GlossaryCreateParameters {
    /**
     * Name of the glossary
     * @type {string}
     * @memberof GlossaryCreateParameters
     */
    name?: string;
    /**
     * List of project ids the glossary should be assigned to.
     * @type {string}
     * @memberof GlossaryCreateParameters
     */
    projectIds?: string;
    /**
     * List of space ids the glossary should be assigned to.
     * @type {Array<string>}
     * @memberof GlossaryCreateParameters
     */
    spaceIds?: Array<string>;
}

export function GlossaryCreateParametersFromJSON(json: any): GlossaryCreateParameters {
    return GlossaryCreateParametersFromJSONTyped(json, false);
}

export function GlossaryCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlossaryCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'projectIds': !exists(json, 'project_ids') ? undefined : json['project_ids'],
        'spaceIds': !exists(json, 'space_ids') ? undefined : json['space_ids'],
    };
}

export function GlossaryCreateParametersToJSON(value?: GlossaryCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'project_ids': value.projectIds,
        'space_ids': value.spaceIds,
    };
}


