/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The glossary this term belongs to.
 * @export
 * @interface GlossaryTermGlossary
 */
export interface GlossaryTermGlossary {
    /**
     * 
     * @type {string}
     * @memberof GlossaryTermGlossary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GlossaryTermGlossary
     */
    name?: string;
}

export function GlossaryTermGlossaryFromJSON(json: any): GlossaryTermGlossary {
    return GlossaryTermGlossaryFromJSONTyped(json, false);
}

export function GlossaryTermGlossaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlossaryTermGlossary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function GlossaryTermGlossaryToJSON(value?: GlossaryTermGlossary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


