/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationCreate422ResponseErrorsInner
 */
export interface InvitationCreate422ResponseErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof InvitationCreate422ResponseErrorsInner
     */
    resource?: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationCreate422ResponseErrorsInner
     */
    field?: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationCreate422ResponseErrorsInner
     */
    message?: string;
}

export function InvitationCreate422ResponseErrorsInnerFromJSON(json: any): InvitationCreate422ResponseErrorsInner {
    return InvitationCreate422ResponseErrorsInnerFromJSONTyped(json, false);
}

export function InvitationCreate422ResponseErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationCreate422ResponseErrorsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resource': !exists(json, 'resource') ? undefined : json['resource'],
        'field': !exists(json, 'field') ? undefined : json['field'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function InvitationCreate422ResponseErrorsInnerToJSON(value?: InvitationCreate422ResponseErrorsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource': value.resource,
        'field': value.field,
        'message': value.message,
    };
}


