/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobAnnotationShort
 */
export interface JobAnnotationShort {
    /**
     * 
     * @type {string}
     * @memberof JobAnnotationShort
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JobAnnotationShort
     */
    value: string;
}

export function JobAnnotationShortFromJSON(json: any): JobAnnotationShort {
    return JobAnnotationShortFromJSONTyped(json, false);
}

export function JobAnnotationShortFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobAnnotationShort {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function JobAnnotationShortToJSON(value?: JobAnnotationShort | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}


