/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobAnnotationUpdateParameters
 */
export interface JobAnnotationUpdateParameters {
    /**
     * Annotation value
     * @type {string}
     * @memberof JobAnnotationUpdateParameters
     */
    value?: string;
    /**
     * Branch name of the job
     * @type {string}
     * @memberof JobAnnotationUpdateParameters
     */
    branch?: string;
}

export function JobAnnotationUpdateParametersFromJSON(json: any): JobAnnotationUpdateParameters {
    return JobAnnotationUpdateParametersFromJSONTyped(json, false);
}

export function JobAnnotationUpdateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobAnnotationUpdateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
    };
}

export function JobAnnotationUpdateParametersToJSON(value?: JobAnnotationUpdateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'branch': value.branch,
    };
}


