/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BranchName,
    BranchNameFromJSON,
    BranchNameFromJSONTyped,
    BranchNameToJSON,
    JobAnnotationShort,
    JobAnnotationShortFromJSON,
    JobAnnotationShortFromJSONTyped,
    JobAnnotationShortToJSON,
    KeyPreview,
    KeyPreviewFromJSON,
    KeyPreviewFromJSONTyped,
    KeyPreviewToJSON,
    LocalePreview,
    LocalePreviewFromJSON,
    LocalePreviewFromJSONTyped,
    LocalePreviewToJSON,
    ProjectShort,
    ProjectShortFromJSON,
    ProjectShortFromJSONTyped,
    ProjectShortToJSON,
    UserPreview,
    UserPreviewFromJSON,
    UserPreviewFromJSONTyped,
    UserPreviewToJSON,
} from './';

/**
 * 
 * @export
 * @interface JobDetails
 */
export interface JobDetails {
    /**
     * 
     * @type {string}
     * @memberof JobDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDetails
     */
    briefing?: string;
    /**
     * 
     * @type {Date}
     * @memberof JobDetails
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof JobDetails
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDetails
     */
    ticketUrl?: string;
    /**
     * 
     * @type {ProjectShort}
     * @memberof JobDetails
     */
    project?: ProjectShort;
    /**
     * 
     * @type {BranchName}
     * @memberof JobDetails
     */
    branch?: BranchName;
    /**
     * 
     * @type {Date}
     * @memberof JobDetails
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobDetails
     */
    updatedAt?: Date;
    /**
     * The ID of the automation that created this job, or null if the job was created manually.
     * @type {string}
     * @memberof JobDetails
     */
    automationId?: string | null;
    /**
     * The ID of the job template this job was created from, or null if no template was used.
     * @type {string}
     * @memberof JobDetails
     */
    jobTemplateId?: string | null;
    /**
     * The review due date for this job. Returns `null` when the project does not have review workflow enabled.
     * @type {Date}
     * @memberof JobDetails
     */
    reviewDueDate?: Date | null;
    /**
     * 
     * @type {UserPreview}
     * @memberof JobDetails
     */
    owner?: UserPreview;
    /**
     * 
     * @type {string}
     * @memberof JobDetails
     */
    jobTagName?: string;
    /**
     * 
     * @type {Date}
     * @memberof JobDetails
     */
    sourceTranslationsUpdatedAt?: Date;
    /**
     * 
     * @type {LocalePreview}
     * @memberof JobDetails
     */
    sourceLocale?: LocalePreview;
    /**
     * 
     * @type {Array<LocalePreview>}
     * @memberof JobDetails
     */
    locales?: Array<LocalePreview>;
    /**
     * 
     * @type {Array<KeyPreview>}
     * @memberof JobDetails
     */
    keys?: Array<KeyPreview>;
    /**
     * Returned only when `include_annotations=true` is supplied on the request.
     * @type {Array<JobAnnotationShort>}
     * @memberof JobDetails
     */
    annotations?: Array<JobAnnotationShort>;
    /**
     * `true` if the job has been locked by the project\'s job-locking workflow (translations attached to the job are read-only until the job advances). 
     * @type {boolean}
     * @memberof JobDetails
     */
    locked?: boolean;
}

export function JobDetailsFromJSON(json: any): JobDetails {
    return JobDetailsFromJSONTyped(json, false);
}

export function JobDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'briefing': !exists(json, 'briefing') ? undefined : json['briefing'],
        'dueDate': !exists(json, 'due_date') ? undefined : (json['due_date'] === null ? null : new Date(json['due_date'])),
        'state': !exists(json, 'state') ? undefined : json['state'],
        'ticketUrl': !exists(json, 'ticket_url') ? undefined : json['ticket_url'],
        'project': !exists(json, 'project') ? undefined : ProjectShortFromJSON(json['project']),
        'branch': !exists(json, 'branch') ? undefined : BranchNameFromJSON(json['branch']),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'automationId': !exists(json, 'automation_id') ? undefined : json['automation_id'],
        'jobTemplateId': !exists(json, 'job_template_id') ? undefined : json['job_template_id'],
        'reviewDueDate': !exists(json, 'review_due_date') ? undefined : (json['review_due_date'] === null ? null : new Date(json['review_due_date'])),
        'owner': !exists(json, 'owner') ? undefined : UserPreviewFromJSON(json['owner']),
        'jobTagName': !exists(json, 'job_tag_name') ? undefined : json['job_tag_name'],
        'sourceTranslationsUpdatedAt': !exists(json, 'source_translations_updated_at') ? undefined : (new Date(json['source_translations_updated_at'])),
        'sourceLocale': !exists(json, 'source_locale') ? undefined : LocalePreviewFromJSON(json['source_locale']),
        'locales': !exists(json, 'locales') ? undefined : ((json['locales'] as Array<any>).map(LocalePreviewFromJSON)),
        'keys': !exists(json, 'keys') ? undefined : ((json['keys'] as Array<any>).map(KeyPreviewFromJSON)),
        'annotations': !exists(json, 'annotations') ? undefined : ((json['annotations'] as Array<any>).map(JobAnnotationShortFromJSON)),
        'locked': !exists(json, 'locked') ? undefined : json['locked'],
    };
}

export function JobDetailsToJSON(value?: JobDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'briefing': value.briefing,
        'due_date': value.dueDate === undefined ? undefined : (value.dueDate === null ? null : value.dueDate.toISOString()),
        'state': value.state,
        'ticket_url': value.ticketUrl,
        'project': ProjectShortToJSON(value.project),
        'branch': BranchNameToJSON(value.branch),
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'automation_id': value.automationId,
        'job_template_id': value.jobTemplateId,
        'review_due_date': value.reviewDueDate === undefined ? undefined : (value.reviewDueDate === null ? null : value.reviewDueDate.toISOString()),
        'owner': UserPreviewToJSON(value.owner),
        'job_tag_name': value.jobTagName,
        'source_translations_updated_at': value.sourceTranslationsUpdatedAt === undefined ? undefined : (value.sourceTranslationsUpdatedAt.toISOString()),
        'source_locale': LocalePreviewToJSON(value.sourceLocale),
        'locales': value.locales === undefined ? undefined : ((value.locales as Array<any>).map(LocalePreviewToJSON)),
        'keys': value.keys === undefined ? undefined : ((value.keys as Array<any>).map(KeyPreviewToJSON)),
        'annotations': value.annotations === undefined ? undefined : ((value.annotations as Array<any>).map(JobAnnotationShortToJSON)),
        'locked': value.locked,
    };
}


