/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobKeysCreateParameters
 */
export interface JobKeysCreateParameters {
    /**
     * specify the branch to use
     * @type {string}
     * @memberof JobKeysCreateParameters
     */
    branch?: string;
    /**
     * ids of keys that should added to the job
     * @type {Array<string>}
     * @memberof JobKeysCreateParameters
     */
    translationKeyIds?: Array<string>;
}

export function JobKeysCreateParametersFromJSON(json: any): JobKeysCreateParameters {
    return JobKeysCreateParametersFromJSONTyped(json, false);
}

export function JobKeysCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobKeysCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'translationKeyIds': !exists(json, 'translation_key_ids') ? undefined : json['translation_key_ids'],
    };
}

export function JobKeysCreateParametersToJSON(value?: JobKeysCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'translation_key_ids': value.translationKeyIds,
    };
}


