/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobLocaleUpdateParameters
 */
export interface JobLocaleUpdateParameters {
    /**
     * specify the branch to use
     * @type {string}
     * @memberof JobLocaleUpdateParameters
     */
    branch?: string;
    /**
     * locale id
     * @type {string}
     * @memberof JobLocaleUpdateParameters
     */
    localeId?: string;
    /**
     * Array of user ids to be assigned to the job locale
     * @type {Array<string>}
     * @memberof JobLocaleUpdateParameters
     */
    userIds?: Array<string>;
    /**
     * Array of reviewer ids to be assigned to the job locale as reviewers
     * @type {Array<string>}
     * @memberof JobLocaleUpdateParameters
     */
    reviewerIds?: Array<string>;
}

export function JobLocaleUpdateParametersFromJSON(json: any): JobLocaleUpdateParameters {
    return JobLocaleUpdateParametersFromJSONTyped(json, false);
}

export function JobLocaleUpdateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLocaleUpdateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'localeId': !exists(json, 'locale_id') ? undefined : json['locale_id'],
        'userIds': !exists(json, 'user_ids') ? undefined : json['user_ids'],
        'reviewerIds': !exists(json, 'reviewer_ids') ? undefined : json['reviewer_ids'],
    };
}

export function JobLocaleUpdateParametersToJSON(value?: JobLocaleUpdateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'locale_id': value.localeId,
        'user_ids': value.userIds,
        'reviewer_ids': value.reviewerIds,
    };
}


