/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobReopenParameters
 */
export interface JobReopenParameters {
    /**
     * specify the branch to use
     * @type {string}
     * @memberof JobReopenParameters
     */
    branch?: string;
}

export function JobReopenParametersFromJSON(json: any): JobReopenParameters {
    return JobReopenParametersFromJSONTyped(json, false);
}

export function JobReopenParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobReopenParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
    };
}

export function JobReopenParametersToJSON(value?: JobReopenParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
    };
}


