/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Branch,
    BranchFromJSON,
    BranchFromJSONTyped,
    BranchToJSON,
    ProjectShort,
    ProjectShortFromJSON,
    ProjectShortFromJSONTyped,
    ProjectShortToJSON,
} from './';

/**
 * 
 * @export
 * @interface JobTemplate
 */
export interface JobTemplate {
    /**
     * 
     * @type {string}
     * @memberof JobTemplate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobTemplate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof JobTemplate
     */
    briefing?: string;
    /**
     * 
     * @type {ProjectShort}
     * @memberof JobTemplate
     */
    project?: ProjectShort;
    /**
     * 
     * @type {Branch}
     * @memberof JobTemplate
     */
    branch?: Branch;
    /**
     * 
     * @type {Date}
     * @memberof JobTemplate
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobTemplate
     */
    updatedAt?: Date;
}

export function JobTemplateFromJSON(json: any): JobTemplate {
    return JobTemplateFromJSONTyped(json, false);
}

export function JobTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'briefing': !exists(json, 'briefing') ? undefined : json['briefing'],
        'project': !exists(json, 'project') ? undefined : ProjectShortFromJSON(json['project']),
        'branch': !exists(json, 'branch') ? undefined : BranchFromJSON(json['branch']),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function JobTemplateToJSON(value?: JobTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'briefing': value.briefing,
        'project': ProjectShortToJSON(value.project),
        'branch': BranchToJSON(value.branch),
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}


