/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobTemplateLocaleUpdateParameters
 */
export interface JobTemplateLocaleUpdateParameters {
    /**
     * specify the branch to use
     * @type {string}
     * @memberof JobTemplateLocaleUpdateParameters
     */
    branch?: string;
    /**
     * locale id
     * @type {string}
     * @memberof JobTemplateLocaleUpdateParameters
     */
    localeId: string;
    /**
     * Array of user ids to be assigned to the job template locale
     * @type {Array<string>}
     * @memberof JobTemplateLocaleUpdateParameters
     */
    userIds?: Array<string>;
    /**
     * Array of reviewer ids to be assigned to the job template locale
     * @type {Array<string>}
     * @memberof JobTemplateLocaleUpdateParameters
     */
    reviewerIds?: Array<string>;
}

export function JobTemplateLocaleUpdateParametersFromJSON(json: any): JobTemplateLocaleUpdateParameters {
    return JobTemplateLocaleUpdateParametersFromJSONTyped(json, false);
}

export function JobTemplateLocaleUpdateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobTemplateLocaleUpdateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'localeId': json['locale_id'],
        'userIds': !exists(json, 'user_ids') ? undefined : json['user_ids'],
        'reviewerIds': !exists(json, 'reviewer_ids') ? undefined : json['reviewer_ids'],
    };
}

export function JobTemplateLocaleUpdateParametersToJSON(value?: JobTemplateLocaleUpdateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'locale_id': value.localeId,
        'user_ids': value.userIds,
        'reviewer_ids': value.reviewerIds,
    };
}


