/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobTemplateUpdateParameters
 */
export interface JobTemplateUpdateParameters {
    /**
     * specify the branch to use
     * @type {string}
     * @memberof JobTemplateUpdateParameters
     */
    branch?: string;
    /**
     * Job template name
     * @type {string}
     * @memberof JobTemplateUpdateParameters
     */
    name: string;
    /**
     * Briefing for the translators
     * @type {string}
     * @memberof JobTemplateUpdateParameters
     */
    briefing?: string;
}

export function JobTemplateUpdateParametersFromJSON(json: any): JobTemplateUpdateParameters {
    return JobTemplateUpdateParametersFromJSONTyped(json, false);
}

export function JobTemplateUpdateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobTemplateUpdateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'name': json['name'],
        'briefing': !exists(json, 'briefing') ? undefined : json['briefing'],
    };
}

export function JobTemplateUpdateParametersToJSON(value?: JobTemplateUpdateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'name': value.name,
        'briefing': value.briefing,
    };
}


