/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobTemplateUserPreview
 */
export interface JobTemplateUserPreview {
    /**
     * 
     * @type {string}
     * @memberof JobTemplateUserPreview
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobTemplateUserPreview
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof JobTemplateUserPreview
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof JobTemplateUserPreview
     */
    role?: string;
}

export function JobTemplateUserPreviewFromJSON(json: any): JobTemplateUserPreview {
    return JobTemplateUserPreviewFromJSONTyped(json, false);
}

export function JobTemplateUserPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobTemplateUserPreview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function JobTemplateUserPreviewToJSON(value?: JobTemplateUserPreview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
        'name': value.name,
        'role': value.role,
    };
}


