/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyLinksCreateParameters
 */
export interface KeyLinksCreateParameters {
    /**
     * Codes of the keys to link as children. Pass an empty array to mark the parent key without linking any children.
     * @type {Array<string>}
     * @memberof KeyLinksCreateParameters
     */
    childKeyIds: Array<string>;
}

export function KeyLinksCreateParametersFromJSON(json: any): KeyLinksCreateParameters {
    return KeyLinksCreateParametersFromJSONTyped(json, false);
}

export function KeyLinksCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyLinksCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'childKeyIds': json['child_key_ids'],
    };
}

export function KeyLinksCreateParametersToJSON(value?: KeyLinksCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'child_key_ids': value.childKeyIds,
    };
}


