/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyLinksBatchDestroyParameters
 */
export interface KeyLinksBatchDestroyParameters {
    /**
     * Codes of the child keys to unlink. Required when unlink_parent is false or omitted. Ignored when unlink_parent is true.
     * @type {Array<string>}
     * @memberof KeyLinksBatchDestroyParameters
     */
    childKeyIds: Array<string>;
    /**
     * When true, dissolves the entire linked-key group by unlinking all children and removing the group. The child_key_ids field is ignored when this is set to true.
     * @type {boolean}
     * @memberof KeyLinksBatchDestroyParameters
     */
    unlinkParent?: boolean;
    /**
     * Controls what happens to child key translation content after unlinking. keep_content (default) copies the parent translation into each child; remove_content clears each child translation.
     * @type {string}
     * @memberof KeyLinksBatchDestroyParameters
     */
    strategy?: KeyLinksBatchDestroyParametersStrategyEnum;
}

export function KeyLinksBatchDestroyParametersFromJSON(json: any): KeyLinksBatchDestroyParameters {
    return KeyLinksBatchDestroyParametersFromJSONTyped(json, false);
}

export function KeyLinksBatchDestroyParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyLinksBatchDestroyParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'childKeyIds': json['child_key_ids'],
        'unlinkParent': !exists(json, 'unlink_parent') ? undefined : json['unlink_parent'],
        'strategy': !exists(json, 'strategy') ? undefined : json['strategy'],
    };
}

export function KeyLinksBatchDestroyParametersToJSON(value?: KeyLinksBatchDestroyParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'child_key_ids': value.childKeyIds,
        'unlink_parent': value.unlinkParent,
        'strategy': value.strategy,
    };
}

/**
* @export
* @enum {string}
*/
export enum KeyLinksBatchDestroyParametersStrategyEnum {
    KeepContent = 'keep_content',
    RemoveContent = 'remove_content'
}


