/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Account,
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    KeyPreview,
    KeyPreviewFromJSON,
    KeyPreviewFromJSONTyped,
    KeyPreviewToJSON,
    UserPreview,
    UserPreviewFromJSON,
    UserPreviewFromJSONTyped,
    UserPreviewToJSON,
} from './';

/**
 * 
 * @export
 * @interface KeyLink
 */
export interface KeyLink {
    /**
     * The timestamp when the link was created.
     * @type {Date}
     * @memberof KeyLink
     */
    createdAt: Date;
    /**
     * The timestamp when the link was last updated.
     * @type {Date}
     * @memberof KeyLink
     */
    updatedAt: Date;
    /**
     * 
     * @type {UserPreview}
     * @memberof KeyLink
     */
    createdBy: UserPreview;
    /**
     * 
     * @type {UserPreview}
     * @memberof KeyLink
     */
    updatedBy: UserPreview;
    /**
     * 
     * @type {Account}
     * @memberof KeyLink
     */
    account: Account;
    /**
     * 
     * @type {KeyPreview}
     * @memberof KeyLink
     */
    parent: KeyPreview;
    /**
     * The child translation keys linked to the parent.
     * @type {Array<KeyPreview>}
     * @memberof KeyLink
     */
    children: Array<KeyPreview>;
}

export function KeyLinkFromJSON(json: any): KeyLink {
    return KeyLinkFromJSONTyped(json, false);
}

export function KeyLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'createdBy': UserPreviewFromJSON(json['created_by']),
        'updatedBy': UserPreviewFromJSON(json['updated_by']),
        'account': AccountFromJSON(json['account']),
        'parent': KeyPreviewFromJSON(json['parent']),
        'children': ((json['children'] as Array<any>).map(KeyPreviewFromJSON)),
    };
}

export function KeyLinkToJSON(value?: KeyLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
        'created_by': UserPreviewToJSON(value.createdBy),
        'updated_by': UserPreviewToJSON(value.updatedBy),
        'account': AccountToJSON(value.account),
        'parent': KeyPreviewToJSON(value.parent),
        'children': ((value.children as Array<any>).map(KeyPreviewToJSON)),
    };
}


