/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeysTagParameters
 */
export interface KeysTagParameters {
    /**
     * specify the branch to use
     * @type {string}
     * @memberof KeysTagParameters
     */
    branch?: string;
    /**
     * q_description_placeholder
     * @type {string}
     * @memberof KeysTagParameters
     */
    q?: string;
    /**
     * Locale used to determine the translation state of a key when filtering for untranslated or translated keys.
     * @type {string}
     * @memberof KeysTagParameters
     */
    localeId?: string;
    /**
     * Tag or comma-separated list of tags to add to the matching collection of keys
     * @type {string}
     * @memberof KeysTagParameters
     */
    tags?: string;
}

export function KeysTagParametersFromJSON(json: any): KeysTagParameters {
    return KeysTagParametersFromJSONTyped(json, false);
}

export function KeysTagParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeysTagParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'q': !exists(json, 'q') ? undefined : json['q'],
        'localeId': !exists(json, 'locale_id') ? undefined : json['locale_id'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function KeysTagParametersToJSON(value?: KeysTagParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'q': value.q,
        'locale_id': value.localeId,
        'tags': value.tags,
    };
}


