/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalePreview,
    LocalePreviewFromJSON,
    LocalePreviewFromJSONTyped,
    LocalePreviewToJSON,
} from './';

/**
 * 
 * @export
 * @interface Locale
 */
export interface Locale {
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    code?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Locale
     */
    _default?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Locale
     */
    main?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Locale
     */
    rtl?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Locale
     */
    pluralForms?: Array<string>;
    /**
     * 
     * @type {LocalePreview}
     * @memberof Locale
     */
    sourceLocale?: LocalePreview;
    /**
     * 
     * @type {LocalePreview}
     * @memberof Locale
     */
    fallbackLocale?: LocalePreview;
    /**
     * 
     * @type {Date}
     * @memberof Locale
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Locale
     */
    updatedAt?: Date;
}

export function LocaleFromJSON(json: any): Locale {
    return LocaleFromJSONTyped(json, false);
}

export function LocaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locale {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'main': !exists(json, 'main') ? undefined : json['main'],
        'rtl': !exists(json, 'rtl') ? undefined : json['rtl'],
        'pluralForms': !exists(json, 'plural_forms') ? undefined : json['plural_forms'],
        'sourceLocale': !exists(json, 'source_locale') ? undefined : LocalePreviewFromJSON(json['source_locale']),
        'fallbackLocale': !exists(json, 'fallback_locale') ? undefined : LocalePreviewFromJSON(json['fallback_locale']),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function LocaleToJSON(value?: Locale | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'code': value.code,
        'default': value._default,
        'main': value.main,
        'rtl': value.rtl,
        'plural_forms': value.pluralForms,
        'source_locale': LocalePreviewToJSON(value.sourceLocale),
        'fallback_locale': LocalePreviewToJSON(value.fallbackLocale),
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}


