/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineTranslationSettingsUpdateParameters
 */
export interface MachineTranslationSettingsUpdateParameters {
    /**
     * The machine translation engine to use as the account default. Supported values: language_ai_translate, aita_translate, microsoft_translate, google_translate, amazon_translate. Pass null or an empty string to reset to the plan default. 
     * @type {string}
     * @memberof MachineTranslationSettingsUpdateParameters
     */
    defaultService?: string | null;
}

export function MachineTranslationSettingsUpdateParametersFromJSON(json: any): MachineTranslationSettingsUpdateParameters {
    return MachineTranslationSettingsUpdateParametersFromJSONTyped(json, false);
}

export function MachineTranslationSettingsUpdateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineTranslationSettingsUpdateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultService': !exists(json, 'default_service') ? undefined : json['default_service'],
    };
}

export function MachineTranslationSettingsUpdateParametersToJSON(value?: MachineTranslationSettingsUpdateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'default_service': value.defaultService,
    };
}


