/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationJobTemplate
 */
export interface OrganizationJobTemplate {
    /**
     * 
     * @type {string}
     * @memberof OrganizationJobTemplate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationJobTemplate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationJobTemplate
     */
    briefing?: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationJobTemplate
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationJobTemplate
     */
    updatedAt?: Date;
}

export function OrganizationJobTemplateFromJSON(json: any): OrganizationJobTemplate {
    return OrganizationJobTemplateFromJSONTyped(json, false);
}

export function OrganizationJobTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationJobTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'briefing': !exists(json, 'briefing') ? undefined : json['briefing'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function OrganizationJobTemplateToJSON(value?: OrganizationJobTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'briefing': value.briefing,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}


