/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationJobTemplateCreateParameters
 */
export interface OrganizationJobTemplateCreateParameters {
    /**
     * Job template name
     * @type {string}
     * @memberof OrganizationJobTemplateCreateParameters
     */
    name: string;
    /**
     * Briefing for the translators
     * @type {string}
     * @memberof OrganizationJobTemplateCreateParameters
     */
    briefing?: string;
}

export function OrganizationJobTemplateCreateParametersFromJSON(json: any): OrganizationJobTemplateCreateParameters {
    return OrganizationJobTemplateCreateParametersFromJSONTyped(json, false);
}

export function OrganizationJobTemplateCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationJobTemplateCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'briefing': !exists(json, 'briefing') ? undefined : json['briefing'],
    };
}

export function OrganizationJobTemplateCreateParametersToJSON(value?: OrganizationJobTemplateCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'briefing': value.briefing,
    };
}


