/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreTranslation
 */
export interface PreTranslation {
    /**
     * 
     * @type {string}
     * @memberof PreTranslation
     */
    id?: string;
    /**
     * Current execution state of the pre-translation job. Jobs start as `pending` while queued, transition to `running` while executing, and settle to `success` or `error`. 
     * @type {string}
     * @memberof PreTranslation
     */
    status?: PreTranslationStatusEnum;
    /**
     * Resource type that was pre-translated.
     * @type {string}
     * @memberof PreTranslation
     */
    translatableType?: PreTranslationTranslatableTypeEnum;
    /**
     * ID of the targeted resource (locale ID, job ID, key ID, or upload ID).
     * @type {string}
     * @memberof PreTranslation
     */
    translatableId?: string;
    /**
     * Error message. `null` unless the job\'s status is `error`.
     * @type {string}
     * @memberof PreTranslation
     */
    error?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PreTranslation
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PreTranslation
     */
    updatedAt?: Date;
}

export function PreTranslationFromJSON(json: any): PreTranslation {
    return PreTranslationFromJSONTyped(json, false);
}

export function PreTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreTranslation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'translatableType': !exists(json, 'translatable_type') ? undefined : json['translatable_type'],
        'translatableId': !exists(json, 'translatable_id') ? undefined : json['translatable_id'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function PreTranslationToJSON(value?: PreTranslation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': value.status,
        'translatable_type': value.translatableType,
        'translatable_id': value.translatableId,
        'error': value.error,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

/**
* @export
* @enum {string}
*/
export enum PreTranslationStatusEnum {
    Pending = 'pending',
    Running = 'running',
    Success = 'success',
    Error = 'error'
}
/**
* @export
* @enum {string}
*/
export enum PreTranslationTranslatableTypeEnum {
    Locale = 'locale',
    Job = 'job',
    TranslationKey = 'translation_key',
    Upload = 'upload'
}


