/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalePreview,
    LocalePreviewFromJSON,
    LocalePreviewFromJSONTyped,
    LocalePreviewToJSON,
    ProjectLocales1,
    ProjectLocales1FromJSON,
    ProjectLocales1FromJSONTyped,
    ProjectLocales1ToJSON,
    ProjectShort,
    ProjectShortFromJSON,
    ProjectShortFromJSONTyped,
    ProjectShortToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProjectLocales
 */
export interface ProjectLocales {
    /**
     * 
     * @type {string}
     * @memberof ProjectLocales
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectLocales
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectLocales
     */
    mainFormat?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectLocales
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectLocales
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<LocalePreview>}
     * @memberof ProjectLocales
     */
    locales?: Array<LocalePreview>;
}

export function ProjectLocalesFromJSON(json: any): ProjectLocales {
    return ProjectLocalesFromJSONTyped(json, false);
}

export function ProjectLocalesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectLocales {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'mainFormat': !exists(json, 'main_format') ? undefined : json['main_format'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'locales': !exists(json, 'locales') ? undefined : ((json['locales'] as Array<any>).map(LocalePreviewFromJSON)),
    };
}

export function ProjectLocalesToJSON(value?: ProjectLocales | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'main_format': value.mainFormat,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'locales': value.locales === undefined ? undefined : ((value.locales as Array<any>).map(LocalePreviewToJSON)),
    };
}


