/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProjectShort,
    ProjectShortFromJSON,
    ProjectShortFromJSONTyped,
    ProjectShortToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProjectReport
 */
export interface ProjectReport {
    /**
     * 
     * @type {number}
     * @memberof ProjectReport
     */
    localesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectReport
     */
    keysCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectReport
     */
    translationsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectReport
     */
    untranslatedKeysCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectReport
     */
    unverifiedTranslationsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectReport
     */
    reviewedTranslationsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectReport
     */
    managedWordsCount?: number;
    /**
     * 
     * @type {ProjectShort}
     * @memberof ProjectReport
     */
    project?: ProjectShort;
}

export function ProjectReportFromJSON(json: any): ProjectReport {
    return ProjectReportFromJSONTyped(json, false);
}

export function ProjectReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localesCount': !exists(json, 'locales_count') ? undefined : json['locales_count'],
        'keysCount': !exists(json, 'keys_count') ? undefined : json['keys_count'],
        'translationsCount': !exists(json, 'translations_count') ? undefined : json['translations_count'],
        'untranslatedKeysCount': !exists(json, 'untranslated_keys_count') ? undefined : json['untranslated_keys_count'],
        'unverifiedTranslationsCount': !exists(json, 'unverified_translations_count') ? undefined : json['unverified_translations_count'],
        'reviewedTranslationsCount': !exists(json, 'reviewed_translations_count') ? undefined : json['reviewed_translations_count'],
        'managedWordsCount': !exists(json, 'managed_words_count') ? undefined : json['managed_words_count'],
        'project': !exists(json, 'project') ? undefined : ProjectShortFromJSON(json['project']),
    };
}

export function ProjectReportToJSON(value?: ProjectReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locales_count': value.localesCount,
        'keys_count': value.keysCount,
        'translations_count': value.translationsCount,
        'untranslated_keys_count': value.untranslatedKeysCount,
        'unverified_translations_count': value.unverifiedTranslationsCount,
        'reviewed_translations_count': value.reviewedTranslationsCount,
        'managed_words_count': value.managedWordsCount,
        'project': ProjectShortToJSON(value.project),
    };
}


