/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectCreateParameters
 */
export interface ProjectCreateParameters {
    /**
     * Name of the project
     * @type {string}
     * @memberof ProjectCreateParameters
     */
    name?: string;
    /**
     * Main file format specified by its API Extension name. Used for locale downloads if no format is specified. For API Extension names of available file formats see <a href=\"https://support.phrase.com/hc/en-us/articles/5784070560412\">Format Guide</a> or our <a href=\"#formats\">Formats API Endpoint</a>.
     * @type {string}
     * @memberof ProjectCreateParameters
     */
    mainFormat?: string;
    /**
     * Indicates whether the project should share the account\'s translation memory
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    sharesTranslationMemory?: boolean;
    /**
     * Image to identify the project
     * @type {Blob}
     * @memberof ProjectCreateParameters
     */
    projectImage?: Blob;
    /**
     * Indicates whether the project image should be deleted.
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    removeProjectImage?: boolean;
    /**
     * Account ID to specify the actual account the project should be created in. Required if the requesting user is a member of multiple accounts.
     * @type {string}
     * @memberof ProjectCreateParameters
     */
    accountId?: string;
    /**
     * When a source project ID is given, a clone of that project will be created, including all locales, keys and translations as well as the main project settings if they are not defined otherwise through the params.
     * @type {string}
     * @memberof ProjectCreateParameters
     */
    sourceProjectId?: string;
    /**
     * (Optional) Review Workflow. \"simple\" / \"review\". <a href=\"https://support.phrase.com/hc/en-us/articles/5784094755484\">Read more</a>
     * @type {string}
     * @memberof ProjectCreateParameters
     */
    workflow?: string;
    /**
     * (Optional) Enable machine translation support in the project. Required for Autopilot and Smart Suggest
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    machineTranslationEnabled?: boolean;
    /**
     * (Optional) Enable branching in the project
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    enableBranching?: boolean;
    /**
     * (Optional) Protect the master branch in project where branching is enabled
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    protectMasterBranch?: boolean;
    /**
     * (Optional) Otherwise, translators are not allowed to edit translations other than strings
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    enableAllDataTypeTranslationKeysForTranslators?: boolean;
    /**
     * (Optional) We can validate and highlight your ICU messages. <a href=\"https://support.phrase.com/hc/en-us/articles/5822319545116\">Read more</a>
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    enableIcuMessageFormat?: boolean;
    /**
     * (Optional) Displays the input fields for the \'ZERO\' plural form for every key as well although only some languages require the \'ZERO\' explicitly.
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    zeroPluralFormEnabled?: boolean;
    /**
     * (Optional) Autopilot, requires machine_translation_enabled. <a href=\"https://support.phrase.com/hc/en-us/articles/5822187934364\">Read more</a>
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    autotranslateEnabled?: boolean;
    /**
     * (Optional) Requires autotranslate_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    autotranslateCheckNewTranslationKeys?: boolean;
    /**
     * (Optional) Requires autotranslate_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    autotranslateCheckNewUploads?: boolean;
    /**
     * (Optional) Requires autotranslate_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    autotranslateCheckNewLocales?: boolean;
    /**
     * (Optional) Requires autotranslate_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    autotranslateMarkAsUnverified?: boolean;
    /**
     * (Optional) Requires autotranslate_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    autotranslateUseMachineTranslation?: boolean;
    /**
     * (Optional) Requires autotranslate_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    autotranslateUseTranslationMemory?: boolean;
    /**
     * (Optional) Smart Suggest, requires machine_translation_enabled
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    smartSuggestEnabled?: boolean;
    /**
     * (Optional) Requires smart_suggest_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    smartSuggestUseGlossary?: boolean;
    /**
     * (Optional) Requires smart_suggest_enabled to be true
     * @type {boolean}
     * @memberof ProjectCreateParameters
     */
    smartSuggestUseMachineTranslation?: boolean;
}

export function ProjectCreateParametersFromJSON(json: any): ProjectCreateParameters {
    return ProjectCreateParametersFromJSONTyped(json, false);
}

export function ProjectCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'mainFormat': !exists(json, 'main_format') ? undefined : json['main_format'],
        'sharesTranslationMemory': !exists(json, 'shares_translation_memory') ? undefined : json['shares_translation_memory'],
        'projectImage': !exists(json, 'project_image') ? undefined : json['project_image'],
        'removeProjectImage': !exists(json, 'remove_project_image') ? undefined : json['remove_project_image'],
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
        'sourceProjectId': !exists(json, 'source_project_id') ? undefined : json['source_project_id'],
        'workflow': !exists(json, 'workflow') ? undefined : json['workflow'],
        'machineTranslationEnabled': !exists(json, 'machine_translation_enabled') ? undefined : json['machine_translation_enabled'],
        'enableBranching': !exists(json, 'enable_branching') ? undefined : json['enable_branching'],
        'protectMasterBranch': !exists(json, 'protect_master_branch') ? undefined : json['protect_master_branch'],
        'enableAllDataTypeTranslationKeysForTranslators': !exists(json, 'enable_all_data_type_translation_keys_for_translators') ? undefined : json['enable_all_data_type_translation_keys_for_translators'],
        'enableIcuMessageFormat': !exists(json, 'enable_icu_message_format') ? undefined : json['enable_icu_message_format'],
        'zeroPluralFormEnabled': !exists(json, 'zero_plural_form_enabled') ? undefined : json['zero_plural_form_enabled'],
        'autotranslateEnabled': !exists(json, 'autotranslate_enabled') ? undefined : json['autotranslate_enabled'],
        'autotranslateCheckNewTranslationKeys': !exists(json, 'autotranslate_check_new_translation_keys') ? undefined : json['autotranslate_check_new_translation_keys'],
        'autotranslateCheckNewUploads': !exists(json, 'autotranslate_check_new_uploads') ? undefined : json['autotranslate_check_new_uploads'],
        'autotranslateCheckNewLocales': !exists(json, 'autotranslate_check_new_locales') ? undefined : json['autotranslate_check_new_locales'],
        'autotranslateMarkAsUnverified': !exists(json, 'autotranslate_mark_as_unverified') ? undefined : json['autotranslate_mark_as_unverified'],
        'autotranslateUseMachineTranslation': !exists(json, 'autotranslate_use_machine_translation') ? undefined : json['autotranslate_use_machine_translation'],
        'autotranslateUseTranslationMemory': !exists(json, 'autotranslate_use_translation_memory') ? undefined : json['autotranslate_use_translation_memory'],
        'smartSuggestEnabled': !exists(json, 'smart_suggest_enabled') ? undefined : json['smart_suggest_enabled'],
        'smartSuggestUseGlossary': !exists(json, 'smart_suggest_use_glossary') ? undefined : json['smart_suggest_use_glossary'],
        'smartSuggestUseMachineTranslation': !exists(json, 'smart_suggest_use_machine_translation') ? undefined : json['smart_suggest_use_machine_translation'],
    };
}

export function ProjectCreateParametersToJSON(value?: ProjectCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'main_format': value.mainFormat,
        'shares_translation_memory': value.sharesTranslationMemory,
        'project_image': value.projectImage,
        'remove_project_image': value.removeProjectImage,
        'account_id': value.accountId,
        'source_project_id': value.sourceProjectId,
        'workflow': value.workflow,
        'machine_translation_enabled': value.machineTranslationEnabled,
        'enable_branching': value.enableBranching,
        'protect_master_branch': value.protectMasterBranch,
        'enable_all_data_type_translation_keys_for_translators': value.enableAllDataTypeTranslationKeysForTranslators,
        'enable_icu_message_format': value.enableIcuMessageFormat,
        'zero_plural_form_enabled': value.zeroPluralFormEnabled,
        'autotranslate_enabled': value.autotranslateEnabled,
        'autotranslate_check_new_translation_keys': value.autotranslateCheckNewTranslationKeys,
        'autotranslate_check_new_uploads': value.autotranslateCheckNewUploads,
        'autotranslate_check_new_locales': value.autotranslateCheckNewLocales,
        'autotranslate_mark_as_unverified': value.autotranslateMarkAsUnverified,
        'autotranslate_use_machine_translation': value.autotranslateUseMachineTranslation,
        'autotranslate_use_translation_memory': value.autotranslateUseTranslationMemory,
        'smart_suggest_enabled': value.smartSuggestEnabled,
        'smart_suggest_use_glossary': value.smartSuggestUseGlossary,
        'smart_suggest_use_machine_translation': value.smartSuggestUseMachineTranslation,
    };
}


