/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInner,
    QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInnerFromJSON,
    QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInnerFromJSONTyped,
    QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInnerToJSON,
} from './';

/**
 * 
 * @export
 * @interface QualityPerformanceScoreList200ResponseAnyOfData
 */
export interface QualityPerformanceScoreList200ResponseAnyOfData {
    /**
     * 
     * @type {Array<QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInner>}
     * @memberof QualityPerformanceScoreList200ResponseAnyOfData
     */
    translations?: Array<QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInner>;
}

export function QualityPerformanceScoreList200ResponseAnyOfDataFromJSON(json: any): QualityPerformanceScoreList200ResponseAnyOfData {
    return QualityPerformanceScoreList200ResponseAnyOfDataFromJSONTyped(json, false);
}

export function QualityPerformanceScoreList200ResponseAnyOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QualityPerformanceScoreList200ResponseAnyOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'translations': !exists(json, 'translations') ? undefined : ((json['translations'] as Array<any>).map(QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInnerFromJSON)),
    };
}

export function QualityPerformanceScoreList200ResponseAnyOfDataToJSON(value?: QualityPerformanceScoreList200ResponseAnyOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'translations': value.translations === undefined ? undefined : ((value.translations as Array<any>).map(QualityPerformanceScoreList200ResponseAnyOfDataTranslationsInnerToJSON)),
    };
}


