/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepliesListParameters
 */
export interface RepliesListParameters {
    /**
     * Specify the branch to use
     * @type {string}
     * @memberof RepliesListParameters
     */
    branch?: string;
    /**
     * Search query for comment messages
     * @type {string}
     * @memberof RepliesListParameters
     */
    query?: string;
    /**
     * Specify filters to find comments by
     * @type {Array<string>}
     * @memberof RepliesListParameters
     */
    filters?: Array<string>;
}

export function RepliesListParametersFromJSON(json: any): RepliesListParameters {
    return RepliesListParametersFromJSONTyped(json, false);
}

export function RepliesListParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepliesListParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'query': !exists(json, 'query') ? undefined : json['query'],
        'filters': !exists(json, 'filters') ? undefined : json['filters'],
    };
}

export function RepliesListParametersToJSON(value?: RepliesListParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'query': value.query,
        'filters': value.filters,
    };
}


