/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepoSyncImportParameters
 */
export interface RepoSyncImportParameters {
    /**
     * Branch to import from
     * @type {string}
     * @memberof RepoSyncImportParameters
     */
    repositoryBranch?: string;
}

export function RepoSyncImportParametersFromJSON(json: any): RepoSyncImportParameters {
    return RepoSyncImportParametersFromJSONTyped(json, false);
}

export function RepoSyncImportParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoSyncImportParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'repositoryBranch': !exists(json, 'repository_branch') ? undefined : json['repository_branch'],
    };
}

export function RepoSyncImportParametersToJSON(value?: RepoSyncImportParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'repository_branch': value.repositoryBranch,
    };
}


