/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepoSyncExportParameters
 */
export interface RepoSyncExportParameters {
    /**
     * Source branch to open a pull request from
     * @type {string}
     * @memberof RepoSyncExportParameters
     */
    prBranch?: string;
}

export function RepoSyncExportParametersFromJSON(json: any): RepoSyncExportParameters {
    return RepoSyncExportParametersFromJSONTyped(json, false);
}

export function RepoSyncExportParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoSyncExportParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prBranch': !exists(json, 'pr_branch') ? undefined : json['pr_branch'],
    };
}

export function RepoSyncExportParametersToJSON(value?: RepoSyncExportParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pr_branch': value.prBranch,
    };
}


