/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScreenshotCreateParameters
 */
export interface ScreenshotCreateParameters {
    /**
     * specify the branch to use
     * @type {string}
     * @memberof ScreenshotCreateParameters
     */
    branch?: string;
    /**
     * Name of the screenshot
     * @type {string}
     * @memberof ScreenshotCreateParameters
     */
    name?: string;
    /**
     * Description of the screenshot
     * @type {string}
     * @memberof ScreenshotCreateParameters
     */
    description?: string;
    /**
     * Screenshot file
     * @type {Blob}
     * @memberof ScreenshotCreateParameters
     */
    filename?: Blob;
}

export function ScreenshotCreateParametersFromJSON(json: any): ScreenshotCreateParameters {
    return ScreenshotCreateParametersFromJSONTyped(json, false);
}

export function ScreenshotCreateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenshotCreateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
    };
}

export function ScreenshotCreateParametersToJSON(value?: ScreenshotCreateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'name': value.name,
        'description': value.description,
        'filename': value.filename,
    };
}


