/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Coordinates and size of the marker on the screenshot, in pixels. 
 * @export
 * @interface ScreenshotMarkerPresentation
 */
export interface ScreenshotMarkerPresentation {
    /**
     * 
     * @type {number}
     * @memberof ScreenshotMarkerPresentation
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof ScreenshotMarkerPresentation
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof ScreenshotMarkerPresentation
     */
    w?: number;
    /**
     * 
     * @type {number}
     * @memberof ScreenshotMarkerPresentation
     */
    h?: number;
}

export function ScreenshotMarkerPresentationFromJSON(json: any): ScreenshotMarkerPresentation {
    return ScreenshotMarkerPresentationFromJSONTyped(json, false);
}

export function ScreenshotMarkerPresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenshotMarkerPresentation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': !exists(json, 'x') ? undefined : json['x'],
        'y': !exists(json, 'y') ? undefined : json['y'],
        'w': !exists(json, 'w') ? undefined : json['w'],
        'h': !exists(json, 'h') ? undefined : json['h'],
    };
}

export function ScreenshotMarkerPresentationToJSON(value?: ScreenshotMarkerPresentation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
        'w': value.w,
        'h': value.h,
    };
}


