/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TagWithStats1Statistics1,
    TagWithStats1Statistics1FromJSON,
    TagWithStats1Statistics1FromJSONTyped,
    TagWithStats1Statistics1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface TagWithStats1
 */
export interface TagWithStats1 {
    /**
     * 
     * @type {Array<TagWithStats1Statistics1>}
     * @memberof TagWithStats1
     */
    statistics?: Array<TagWithStats1Statistics1>;
}

export function TagWithStats1FromJSON(json: any): TagWithStats1 {
    return TagWithStats1FromJSONTyped(json, false);
}

export function TagWithStats1FromJSONTyped(json: any, ignoreDiscriminator: boolean): TagWithStats1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statistics': !exists(json, 'statistics') ? undefined : ((json['statistics'] as Array<any>).map(TagWithStats1Statistics1FromJSON)),
    };
}

export function TagWithStats1ToJSON(value?: TagWithStats1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statistics': value.statistics === undefined ? undefined : ((value.statistics as Array<any>).map(TagWithStats1Statistics1ToJSON)),
    };
}


