/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagWithStats1Statistics
 */
export interface TagWithStats1Statistics {
    /**
     * 
     * @type {number}
     * @memberof TagWithStats1Statistics
     */
    keysTotalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TagWithStats1Statistics
     */
    translationsCompletedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TagWithStats1Statistics
     */
    translationsUnverifiedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TagWithStats1Statistics
     */
    keysUntranslatedCount?: number;
}

export function TagWithStats1StatisticsFromJSON(json: any): TagWithStats1Statistics {
    return TagWithStats1StatisticsFromJSONTyped(json, false);
}

export function TagWithStats1StatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagWithStats1Statistics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keysTotalCount': !exists(json, 'keys_total_count') ? undefined : json['keys_total_count'],
        'translationsCompletedCount': !exists(json, 'translations_completed_count') ? undefined : json['translations_completed_count'],
        'translationsUnverifiedCount': !exists(json, 'translations_unverified_count') ? undefined : json['translations_unverified_count'],
        'keysUntranslatedCount': !exists(json, 'keys_untranslated_count') ? undefined : json['keys_untranslated_count'],
    };
}

export function TagWithStats1StatisticsToJSON(value?: TagWithStats1Statistics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keys_total_count': value.keysTotalCount,
        'translations_completed_count': value.translationsCompletedCount,
        'translations_unverified_count': value.translationsUnverifiedCount,
        'keys_untranslated_count': value.keysUntranslatedCount,
    };
}


