/* tslint:disable */
/* eslint-disable */
/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadSummary
 */
export interface UploadSummary {
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    localesCreated?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    translationKeysCreated?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    translationKeysUpdated?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    translationKeysUnmentioned?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    translationsCreated?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    translationsUpdated?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    tagsCreated?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadSummary
     */
    translationKeysIgnored?: number;
}

export function UploadSummaryFromJSON(json: any): UploadSummary {
    return UploadSummaryFromJSONTyped(json, false);
}

export function UploadSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localesCreated': !exists(json, 'locales_created') ? undefined : json['locales_created'],
        'translationKeysCreated': !exists(json, 'translation_keys_created') ? undefined : json['translation_keys_created'],
        'translationKeysUpdated': !exists(json, 'translation_keys_updated') ? undefined : json['translation_keys_updated'],
        'translationKeysUnmentioned': !exists(json, 'translation_keys_unmentioned') ? undefined : json['translation_keys_unmentioned'],
        'translationsCreated': !exists(json, 'translations_created') ? undefined : json['translations_created'],
        'translationsUpdated': !exists(json, 'translations_updated') ? undefined : json['translations_updated'],
        'tagsCreated': !exists(json, 'tags_created') ? undefined : json['tags_created'],
        'translationKeysIgnored': !exists(json, 'translation_keys_ignored') ? undefined : json['translation_keys_ignored'],
    };
}

export function UploadSummaryToJSON(value?: UploadSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locales_created': value.localesCreated,
        'translation_keys_created': value.translationKeysCreated,
        'translation_keys_updated': value.translationKeysUpdated,
        'translation_keys_unmentioned': value.translationKeysUnmentioned,
        'translations_created': value.translationsCreated,
        'translations_updated': value.translationsUpdated,
        'tags_created': value.tagsCreated,
        'translation_keys_ignored': value.translationKeysIgnored,
    };
}


