/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VariableUpdateParameters
 */
export interface VariableUpdateParameters {
    /**
     * Name of the variable
     * @type {string}
     * @memberof VariableUpdateParameters
     */
    name?: string;
    /**
     * Value of the variable
     * @type {string}
     * @memberof VariableUpdateParameters
     */
    value?: string;
}

export function VariableUpdateParametersFromJSON(json: any): VariableUpdateParameters {
    return VariableUpdateParametersFromJSONTyped(json, false);
}

export function VariableUpdateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariableUpdateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function VariableUpdateParametersToJSON(value?: VariableUpdateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}


