/* tslint:disable */
/* eslint-disable */
/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Webhook
 */
export interface Webhook {
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    callbackUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Webhook
     */
    events?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Webhook
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Webhook
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Webhook
     */
    updatedAt?: Date;
}

export function WebhookFromJSON(json: any): Webhook {
    return WebhookFromJSONTyped(json, false);
}

export function WebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webhook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'callbackUrl': !exists(json, 'callback_url') ? undefined : json['callback_url'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'events': !exists(json, 'events') ? undefined : json['events'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function WebhookToJSON(value?: Webhook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'callback_url': value.callbackUrl,
        'description': value.description,
        'events': value.events,
        'active': value.active,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}


